---
- hosts: all
  become: yes
  tasks:
  - name: Stop redis services 
    service:
     name: "{{ item }}"
     state: stopped
    with_items:
        - redis-master.service
        - redis-slave.service

  - name: Delete systemd unit files
    file: 
     path: /usr/lib/systemd/system/"{{ item }}"
     state: absent
    with_items:
      - redis-master.service 
      - redis-slave.service 

  - name: Delete redis directory
    shell: rm -rf /data/redis
